### ISSUE TITLE
Can not be used in ia32 packaged application

### ISSUE THREAD

**Issue by GrumpyCrouton** [fcannizzaro/win-audio#6]
When trying to use this module in an Electron application which is packaged as ia32 (32bit), I get the following error

```
Uncaught Error: \\?\F:\edc\v2\32bit\resources\app\node_modules\win-audio\build\Release\audio.node is not a valid Win32 application.
\\?\F:\edc\v2\32bit\resources\app\node_modules\win-audio\build\Release\audio.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602)
    at tryModuleLoad (internal/modules/cjs/loader.js:541)
    at Function.Module._load (internal/modules/cjs/loader.js:533)
    at Module.require (internal/modules/cjs/loader.js:640)
    at require (internal/modules/cjs/helpers.js:20)
    at Object.<anonymous> (F:\edc\v2\32bit\resources\app\node_modules\win-audio\dist\index.js:5)
    at Object.<anonymous> (F:\edc\v2\32bit\resources\app\node_modules\win-audio\dist\index.js:139)
    at Module._compile (internal/modules/cjs/loader.js:693)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704)
    at Module.load (internal/modules/cjs/loader.js:602)
    at tryModuleLoad (internal/modules/cjs/loader.js:541)
    at Function.Module._load (internal/modules/cjs/loader.js:533)
    at Module.require (internal/modules/cjs/loader.js:640)
```

**Comment by fcannizzaro** [comment]
you can run

```sh
npx electron-rebuild . --arch=ia32
```

to rebuild native module to 32 bit arch, before run the packager.

**Comment by GrumpyCrouton** [comment]
I'll try this and let you know my results.

**Comment by GrumpyCrouton** [comment]
I tried this using the command `npx electron-rebuild . --arch=ia32 -v v1.4.13`, with electron-rebuild as a dev dependency and I get the following error:

```
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.11.1 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.4.13/iojs-v1.4.13.tar.gz
gyp http 200 https://atom.io/download/electron/v1.4.13/iojs-v1.4.13.tar.gz
gyp http GET https://atom.io/download/electron/v1.4.13/SHASUMS256.txt
gyp http GET https://atom.io/download/electron/v1.4.13/win-x86/iojs.lib
gyp http GET https://atom.io/download/electron/v1.4.13/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.4.13/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.4.13/win-x86/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.4.13/SHASUMS256.txt
gyp info spawn C:\Users\roadmin.DT-GKBT322.002\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Users\\roadmin.DT-GKBT322.002\\AppData\\Roaming\\npm-cache\\_npx\\6476\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Electron\\NEW\\DC-GEN2\\node_modules\\win-audio\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\roadmin.DT-GKBT322.002\\AppData\\Roaming\\npm-cache\\_npx\\6476\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\roadmin.DT-GKBT322.002\\.electron-gyp\\iojs-1.4.13\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\roadmin.DT-GKBT322.002\\.electron-gyp\\iojs-1.4.13',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\roadmin.DT-GKBT322.002\\AppData\\Roaming\\npm-cache\\_npx\\6476\\node_modules\\electron-rebuild\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\roadmin.DT-GKBT322.002\\.electron-gyp\\iojs-1.4.13\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Electron\\NEW\\DC-GEN2\\node_modules\\win-audio',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Electron\\NEW\\DC-GEN2\\node_modules\\win-audio\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  audio-napi.cc
  win_delay_load_hook.cc
d:\electron\new\dc-gen2\node_modules\win-audio\audio-napi.cc(7): fatal error C1083: Cannot open include file: 'node_api.h': No such file or directory [D:\Electron\NEW\DC-GEN2\node_modules\win-audio\build\audio.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\roadmin.DT-GKBT322.002\AppData\Roaming\npm-cache\_npx\6476\node_modules\electron-rebuild\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\roadmin.DT-GKBT322.002\\AppData\\Roaming\\npm-cache\\_npx\\6476\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=v1.4.13" "--arch=ia32" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd D:\Electron\NEW\DC-GEN2\node_modules\win-audio
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.11.1 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.4.13/iojs-v1.4.13.tar.gz
gyp http 200 https://atom.io/download/electron/v1.4.13/iojs-v1.4.13.tar.gz
gyp http GET https://atom.io/download/electron/v1.4.13/SHASUMS256.txt
gyp http GET https://atom.io/download/electron/v1.4.13/win-x86/iojs.lib
gyp http GET https://atom.io/download/electron/v1.4.13/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.4.13/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.4.13/win-x86/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.4.13/SHASUMS256.txt
gyp info spawn C:\Users\roadmin.DT-GKBT322.002\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Users\\roadmin.DT-GKBT322.002\\AppData\\Roaming\\npm-cache\\_npx\\6476\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Electron\\NEW\\DC-GEN2\\node_modules\\win-audio\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\roadmin.DT-GKBT322.002\\AppData\\Roaming\\npm-cache\\_npx\\6476\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\roadmin.DT-GKBT322.002\\.electron-gyp\\iojs-1.4.13\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\roadmin.DT-GKBT322.002\\.electron-gyp\\iojs-1.4.13',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\roadmin.DT-GKBT322.002\\AppData\\Roaming\\npm-cache\\_npx\\6476\\node_modules\\electron-rebuild\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\roadmin.DT-GKBT322.002\\.electron-gyp\\iojs-1.4.13\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Electron\\NEW\\DC-GEN2\\node_modules\\win-audio',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Electron\\NEW\\DC-GEN2\\node_modules\\win-audio\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  audio-napi.cc
  win_delay_load_hook.cc
d:\electron\new\dc-gen2\node_modules\win-audio\audio-napi.cc(7): fatal error C1083: Cannot open include file: 'node_api.h': No such file or directory [D:\Electron\NEW\DC-GEN2\node_modules\win-audio\build\audio.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\roadmin.DT-GKBT322.002\AppData\Roaming\npm-cache\_npx\6476\node_modules\electron-rebuild\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\roadmin.DT-GKBT322.002\\AppData\\Roaming\\npm-cache\\_npx\\6476\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=v1.4.13" "--arch=ia32" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd D:\Electron\NEW\DC-GEN2\node_modules\win-audio
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\Users\roadmin.DT-GKBT322.002\AppData\Roaming\npm-cache\_npx\6476\node_modules\electron-rebuild\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (C:\Users\roadmin.DT-GKBT322.002\AppData\Roaming\npm-cache\_npx\6476\node_modules\electron-rebuild\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.error (C:\Users\roadmin.DT-GKBT322.002\AppData\Roaming\npm-cache\_npx\6476\node_modules\electron-rebuild\node_modules\rxjs\internal\Subscriber.js:158:26)
    at Subscriber._error (C:\Users\roadmin.DT-GKBT322.002\AppData\Roaming\npm-cache\_npx\6476\node_modules\electron-rebuild\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (C:\Users\roadmin.DT-GKBT322.002\AppData\Roaming\npm-cache\_npx\6476\node_modules\electron-rebuild\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (C:\Users\roadmin.DT-GKBT322.002\AppData\Roaming\npm-cache\_npx\6476\node_modules\electron-rebuild\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (C:\Users\roadmin.DT-GKBT322.002\AppData\Roaming\npm-cache\_npx\6476\node_modules\electron-rebuild\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (C:\Users\roadmin.DT-GKBT322.002\AppData\Roaming\npm-cache\_npx\6476\node_modules\electron-rebuild\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (C:\Users\roadmin.DT-GKBT322.002\AppData\Roaming\npm-cache\_npx\6476\node_modules\electron-rebuild\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.next (C:\Users\roadmin.DT-GKBT322.002\AppData\Roaming\npm-cache\_npx\6476\node_modules\electron-rebuild\node_modules\rxjs\internal\Subscriber.js:145:22)
```

It says ` No such file or directory [D:\Electron\NEW\DC-GEN2\node_modules\win-audio\build\audio.vcxproj` but that file is in that location. Any suggestion?

**Comment by GrumpyCrouton** [comment]
Great! This works and I'm able to package and run this in ia32 now.

However, now I get an error when I try to run `npm start` for testing purposes before packaging; 

![image](https://user-images.githubusercontent.com/12193403/54371790-03643800-4648-11e9-9482-0a9dd2a8cb90.png)

I didn't get this error before, and if I remove win-audio and reinstall it without rebuilding it to ia32, I also don't get this error.

**Comment by GrumpyCrouton** [comment]
Great, I got this to work with your help. However, now if it runs using x64 architecture, I get the original error as above. Is there any way to make it work on both x64 and ia32?

For now, I just added the rebuild command to my scripts, but I'd like to avoid that.

```
"scripts": {
    "start": "npx electron-rebuild . --arch=x64 && electron .",
    "compile64": "npx electron-rebuild . --arch=x64 && electron-packager . --overwrite",
    "compile32": "npx electron-rebuild . --arch=ia32 && electron-packager . --arch=ia32 --overwrite",
    "compile-all": "npm run compile64 && npm run compile32"
  },
```

**Comment by fcannizzaro** [comment]
I believe there is no way to build for 32/64 bit at the same time.
